'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'en' | 'fr' | 'ar'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.products': 'Products',
    'nav.quality': 'Quality',
    'nav.contact': 'Contact',
    'home.hero.title': 'Premium Algerian Products',
    'home.hero.subtitle': 'Exporting Excellence Since 1998',
    'home.hero.description': 'Discover our premium selection of dates, olive oil, and traditional spices from Algeria',
    'home.hero.cta': 'Explore Products',
    'home.featured.title': 'Featured Products',
    'home.about.title': 'About 1000 Coupole Export',
    'home.about.description': 'We are a leading exporter of premium Algerian products, committed to delivering excellence in every shipment.',
    'home.why.title': 'Why Choose Us',
    'home.why.quality': 'Premium Quality',
    'home.why.quality.desc': 'ISO 22000 & HACCP certified products',
    'home.why.global': 'Global Reach',
    'home.why.global.desc': 'Exporting to over 20 countries worldwide',
    'home.why.trusted': 'Trusted Partner',
    'home.why.trusted.desc': 'Over 15 years of excellence',
    'contact.title': 'Contact Us',
    'contact.name': 'Full Name',
    'contact.company': 'Company Name',
    'contact.email': 'Email Address',
    'contact.phone': 'Phone Number',
    'contact.country': 'Country',
    'contact.message': 'Message',
    'contact.submit': 'Send Message',
    'products.all': 'All Products',
    'products.category': 'Category',
    'products.viewDetails': 'View Details',
    'products.loading': 'Loading products...',
    'products.none': 'No products available at the moment.',
    // About Page
    'about.title': 'About Us',
    'about.subtitle': 'Leading exporter of premium Algerian products to the world',
    'about.story': 'Our Story',
    'about.story.p1': '1000 Coupole Export has been at the forefront of Algerian agricultural exports for over 15 years. We specialize in sourcing and exporting the finest quality dates, olive oil, spices, and other premium products.',
    'about.story.p2': 'Our commitment to quality, sustainability, and customer satisfaction has made us a trusted partner for importers and distributors worldwide.',
    'about.story.p3': 'We work directly with local farmers and producers to ensure the highest standards of quality while supporting sustainable agricultural practices.',
    'about.mission': 'Our Mission',
    'about.mission.text': 'To share the authentic taste of Algeria with the world by providing premium quality products that meet international standards while preserving traditional production methods.',
    'about.vision': 'Our Vision',
    'about.vision.text': 'To become the leading exporter of Algerian agricultural products, recognized globally for our commitment to quality, sustainability, and innovation.',
    'about.values': 'Our Values',
    'about.values.quality': 'Quality First',
    'about.values.quality.desc': 'We never compromise on quality, ensuring every product meets the highest standards',
    'about.values.customer': 'Customer Focus',
    'about.values.customer.desc': 'Our customers\' success is our priority, and we build lasting partnerships',
    'about.values.integrity': 'Integrity',
    'about.values.integrity.desc': 'We operate with honesty, transparency, and ethical business practices',
    'about.values.sustainability': 'Sustainability',
    'about.values.sustainability.desc': 'We support sustainable farming practices that protect our environment',
    'about.stats.experience': 'Years Experience',
    'about.stats.countries': 'Countries Served',
    'about.stats.clients': 'Happy Clients',
    'about.stats.quality': 'Quality Guaranteed',
    // Quality Page
    'quality.title': 'Quality & Certifications',
    'quality.subtitle': 'Meeting international standards with every shipment',
    'quality.commitment': 'Our Quality Commitment',
    'quality.testing': 'Rigorous Testing',
    'quality.testing.desc': 'Every batch undergoes comprehensive quality control testing to ensure it meets our strict standards and customer requirements.',
    'quality.certified': 'Certified Excellence',
    'quality.certified.desc': 'We maintain all major international food safety and quality certifications to guarantee the highest standards.',
    'quality.traceability': 'Full Traceability',
    'quality.traceability.desc': 'Complete traceability from farm to export, ensuring transparency and accountability at every step.',
    'quality.laboratory': 'Laboratory Analysis',
    'quality.laboratory.desc': 'Advanced laboratory testing for contaminants, quality parameters, and compliance with international regulations.',
    'quality.certifications': 'Our Certifications',
    'quality.iso': 'Food Safety Management System certification ensuring safe food production and handling',
    'quality.haccp': 'Hazard Analysis and Critical Control Points system for food safety',
    'quality.organic': 'Certified organic products available upon request for select items',
    'quality.process': 'Our Quality Process',
    'quality.step1': 'Source Selection',
    'quality.step1.desc': 'We carefully select suppliers and farms that meet our quality standards and share our commitment to excellence.',
    'quality.step2': 'Quality Inspection',
    'quality.step2.desc': 'Products undergo thorough inspection for quality, freshness, and compliance with specifications.',
    'quality.step3': 'Processing & Packaging',
    'quality.step3.desc': 'State-of-the-art processing facilities ensure products are handled with care and packaged to maintain freshness.',
    'quality.step4': 'Final Testing',
    'quality.step4.desc': 'Comprehensive laboratory testing before shipment to verify quality parameters and safety standards.',
    'quality.step5': 'Export & Documentation',
    'quality.step5.desc': 'Complete documentation and certificates provided with each shipment for full compliance and traceability.',
    // Contact Page
    'contact.subtitle': 'Get in touch with us for inquiries and orders',
    'contact.getintouch': 'Get In Touch',
    'contact.intro': 'We\'re here to help! Contact us for product inquiries, quotes, or any questions about our services.',
    'contact.address': 'Address',
    'contact.hours': 'Business Hours',
    'contact.hours.weekdays': 'Monday - Friday: 9:00 AM - 6:00 PM',
    'contact.hours.saturday': 'Saturday: 9:00 AM - 1:00 PM',
    'contact.hours.sunday': 'Sunday: Closed',
    'contact.form.title': 'Send Us a Message',
    'contact.form.name.label': 'Name',
    'contact.form.name.placeholder': 'Your name',
    'contact.form.email.label': 'Email',
    'contact.form.email.placeholder': 'your@email.com',
    'contact.form.company.label': 'Company',
    'contact.form.company.placeholder': 'Your company',
    'contact.form.message.label': 'Message',
    'contact.form.message.placeholder': 'Your message...',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.about': 'À Propos',
    'nav.products': 'Produits',
    'nav.quality': 'Qualité',
    'nav.contact': 'Contact',
    'home.hero.title': 'Produits Algériens de Qualité',
    'home.hero.subtitle': 'Excellence d\'Exportation Depuis 1998',
    'home.hero.description': 'Découvrez notre sélection premium de dattes, huile d\'olive et épices traditionnelles d\'Algérie',
    'home.hero.cta': 'Explorer les Produits',
    'home.featured.title': 'Produits Vedettes',
    'home.about.title': 'À Propos de 1000 Coupole Export',
    'home.about.description': 'Nous sommes un exportateur leader de produits algériens de qualité, engagés à offrir l\'excellence dans chaque envoi.',
    'home.why.title': 'Pourquoi Nous Choisir',
    'home.why.quality': 'Qualité Premium',
    'home.why.quality.desc': 'Produits certifiés ISO 22000 et HACCP',
    'home.why.global': 'Portée Mondiale',
    'home.why.global.desc': 'Exportation vers plus de 20 pays',
    'home.why.trusted': 'Partenaire de Confiance',
    'home.why.trusted.desc': 'Plus de 15 ans d\'excellence',
    'contact.title': 'Nous Contacter',
    'contact.name': 'Nom Complet',
    'contact.company': 'Nom de l\'Entreprise',
    'contact.email': 'Adresse Email',
    'contact.phone': 'Numéro de Téléphone',
    'contact.country': 'Pays',
    'contact.message': 'Message',
    'contact.submit': 'Envoyer le Message',
    'products.all': 'Tous les Produits',
    'products.category': 'Catégorie',
    'products.viewDetails': 'Voir les Détails',
    'products.loading': 'Chargement des produits...',
    'products.none': 'Aucun produit disponible pour le moment.',
    // About Page
    'about.title': 'À Propos',
    'about.subtitle': 'Premier exportateur de produits algériens de qualité',
    'about.story': 'Notre Histoire',
    'about.story.p1': '1000 Coupole Export est à l\'avant-garde des exportations agricoles algériennes depuis plus de 15 ans. Nous nous spécialisons dans l\'approvisionnement et l\'exportation de dattes, d\'huile d\'olive, d\'épices et d\'autres produits premium de la plus haute qualité.',
    'about.story.p2': 'Notre engagement envers la qualité, la durabilité et la satisfaction client a fait de nous un partenaire de confiance pour les importateurs et distributeurs du monde entier.',
    'about.story.p3': 'Nous travaillons directement avec les agriculteurs et producteurs locaux pour garantir les plus hauts standards de qualité tout en soutenant des pratiques agricoles durables.',
    'about.mission': 'Notre Mission',
    'about.mission.text': 'Partager le goût authentique de l\'Algérie avec le monde en fournissant des produits de qualité supérieure qui répondent aux normes internationales tout en préservant les méthodes de production traditionnelles.',
    'about.vision': 'Notre Vision',
    'about.vision.text': 'Devenir le principal exportateur de produits agricoles algériens, reconnu mondialement pour notre engagement envers la qualité, la durabilité et l\'innovation.',
    'about.values': 'Nos Valeurs',
    'about.values.quality': 'Qualité Avant Tout',
    'about.values.quality.desc': 'Nous ne faisons jamais de compromis sur la qualité, garantissant que chaque produit répond aux plus hauts standards',
    'about.values.customer': 'Focus Client',
    'about.values.customer.desc': 'Le succès de nos clients est notre priorité, et nous construisons des partenariats durables',
    'about.values.integrity': 'Intégrité',
    'about.values.integrity.desc': 'Nous opérons avec honnêteté, transparence et pratiques commerciales éthiques',
    'about.values.sustainability': 'Durabilité',
    'about.values.sustainability.desc': 'Nous soutenons des pratiques agricoles durables qui protègent notre environnement',
    'about.stats.experience': 'Ans d\'Expérience',
    'about.stats.countries': 'Pays Desservis',
    'about.stats.clients': 'Clients Satisfaits',
    'about.stats.quality': 'Qualité Garantie',
    // Quality Page
    'quality.title': 'Qualité & Certifications',
    'quality.subtitle': 'Respecter les normes internationales à chaque envoi',
    'quality.commitment': 'Notre Engagement Qualité',
    'quality.testing': 'Tests Rigoureux',
    'quality.testing.desc': 'Chaque lot subit des tests de contrôle qualité complets pour s\'assurer qu\'il répond à nos normes strictes et aux exigences des clients.',
    'quality.certified': 'Excellence Certifiée',
    'quality.certified.desc': 'Nous maintenons toutes les principales certifications internationales de sécurité et de qualité alimentaire pour garantir les plus hauts standards.',
    'quality.traceability': 'Traçabilité Complète',
    'quality.traceability.desc': 'Traçabilité complète de la ferme à l\'export, garantissant transparence et responsabilité à chaque étape.',
    'quality.laboratory': 'Analyse en Laboratoire',
    'quality.laboratory.desc': 'Tests de laboratoire avancés pour les contaminants, paramètres de qualité et conformité aux réglementations internationales.',
    'quality.certifications': 'Nos Certifications',
    'quality.iso': 'Certification du système de gestion de la sécurité alimentaire garantissant une production et manipulation sûres',
    'quality.haccp': 'Système d\'analyse des risques et points critiques pour le contrôle de la sécurité alimentaire',
    'quality.organic': 'Produits biologiques certifiés disponibles sur demande pour certains articles',
    'quality.process': 'Notre Processus Qualité',
    'quality.step1': 'Sélection des Sources',
    'quality.step1.desc': 'Nous sélectionnons soigneusement les fournisseurs et fermes qui répondent à nos standards de qualité et partagent notre engagement envers l\'excellence.',
    'quality.step2': 'Inspection Qualité',
    'quality.step2.desc': 'Les produits subissent une inspection approfondie pour la qualité, la fraîcheur et la conformité aux spécifications.',
    'quality.step3': 'Traitement & Emballage',
    'quality.step3.desc': 'Des installations de traitement de pointe garantissent que les produits sont manipulés avec soin et emballés pour maintenir la fraîcheur.',
    'quality.step4': 'Tests Finaux',
    'quality.step4.desc': 'Tests de laboratoire complets avant expédition pour vérifier les paramètres de qualité et les normes de sécurité.',
    'quality.step5': 'Export & Documentation',
    'quality.step5.desc': 'Documentation complète et certificats fournis avec chaque envoi pour une conformité et traçabilité totales.',
    // Contact Page
    'contact.subtitle': 'Contactez-nous pour vos demandes et commandes',
    'contact.getintouch': 'Contactez-Nous',
    'contact.intro': 'Nous sommes là pour vous aider ! Contactez-nous pour des demandes de produits, devis ou toute question sur nos services.',
    'contact.address': 'Adresse',
    'contact.hours': 'Heures d\'Ouverture',
    'contact.hours.weekdays': 'Lundi - Vendredi: 9:00 - 18:00',
    'contact.hours.saturday': 'Samedi: 9:00 - 13:00',
    'contact.hours.sunday': 'Dimanche: Fermé',
    'contact.form.title': 'Envoyez-Nous un Message',
    'contact.form.name.label': 'Nom',
    'contact.form.name.placeholder': 'Votre nom',
    'contact.form.email.label': 'Email',
    'contact.form.email.placeholder': 'votre@email.com',
    'contact.form.company.label': 'Entreprise',
    'contact.form.company.placeholder': 'Votre entreprise',
    'contact.form.message.label': 'Message',
    'contact.form.message.placeholder': 'Votre message...',
  },
  ar: {
    'nav.home': 'الرئيسية',
    'nav.about': 'من نحن',
    'nav.products': 'المنتجات',
    'nav.quality': 'الجودة',
    'nav.contact': 'اتصل بنا',
    'home.hero.title': 'منتجات جزائرية فاخرة',
    'home.hero.subtitle': 'التميز في التصدير منذ 1998',
    'home.hero.description': 'اكتشف مجموعتنا المميزة من التمور وزيت الزيتون والتوابل التقليدية من الجزائر',
    'home.hero.cta': 'استكشف المنتجات',
    'home.featured.title': 'المنتجات المميزة',
    'home.about.title': 'حول 1000 قبة للتصدير',
    'home.about.description': 'نحن مصدر رائد للمنتجات الجزائرية الممتازة، ملتزمون بتقديم التميز في كل شحنة.',
    'home.why.title': 'لماذا تختارنا',
    'home.why.quality': 'جودة فاخرة',
    'home.why.quality.desc': 'منتجات معتمدة ISO 22000 و HACCP',
    'home.why.global': 'انتشار عالمي',
    'home.why.global.desc': 'التصدير إلى أكثر من 20 دولة حول العالم',
    'home.why.trusted': 'شريك موثوق',
    'home.why.trusted.desc': 'أكثر من 15 عاماً من التميز',
    'contact.title': 'اتصل بنا',
    'contact.name': 'الاسم الكامل',
    'contact.company': 'اسم الشركة',
    'contact.email': 'البريد الإلكتروني',
    'contact.phone': 'رقم الهاتف',
    'contact.country': 'الدولة',
    'contact.message': 'الرسالة',
    'contact.submit': 'إرسال الرسالة',
    'products.all': 'جميع المنتجات',
    'products.category': 'الفئة',
    'products.viewDetails': 'عرض التفاصيل',
    'products.loading': 'جاري تحميل المنتجات...',
    'products.none': 'لا توجد منتجات متاحة في الوقت الحالي.',
    // About Page
    'about.title': 'من نحن',
    'about.subtitle': 'المصدر الرائد للمنتجات الجزائرية الممتازة للعالم',
    'about.story': 'قصتنا',
    'about.story.p1': 'كانت 1000 قبة للتصدير في طليعة الصادرات الزراعية الجزائرية لأكثر من 15 عامًا. نحن متخصصون في توريد وتصدير أجود أنواع التمور وزيت الزيتون والتوابل والمنتجات الممتازة الأخرى.',
    'about.story.p2': 'التزامنا بالجودة والاستدامة ورضا العملاء جعلنا شريكًا موثوقًا للمستوردين والموزعين في جميع أنحاء العالم.',
    'about.story.p3': 'نعمل مباشرة مع المزارعين والمنتجين المحليين لضمان أعلى معايير الجودة مع دعم الممارسات الزراعية المستدامة.',
    'about.mission': 'مهمتنا',
    'about.mission.text': 'مشاركة الذوق الأصيل للجزائر مع العالم من خلال توفير منتجات عالية الجودة تلبي المعايير الدولية مع الحفاظ على طرق الإنتاج التقليدية.',
    'about.vision': 'رؤيتنا',
    'about.vision.text': 'أن نصبح المصدر الرائد للمنتجات الزراعية الجزائرية، معترف به عالميًا لالتزامنا بالجودة والاستدامة والابتكار.',
    'about.values': 'قيمنا',
    'about.values.quality': 'الجودة أولاً',
    'about.values.quality.desc': 'نحن لا نساوم أبدًا على الجودة، ونضمن أن كل منتج يلبي أعلى المعايير',
    'about.values.customer': 'التركيز على العملاء',
    'about.values.customer.desc': 'نجاح عملائنا هو أولويتنا، ونبني شراكات دائمة',
    'about.values.integrity': 'النزاهة',
    'about.values.integrity.desc': 'نعمل بصدق وشفافية وممارسات تجارية أخلاقية',
    'about.values.sustainability': 'الاستدامة',
    'about.values.sustainability.desc': 'ندعم الممارسات الزراعية المستدامة التي تحمي بيئتنا',
    'about.stats.experience': 'سنوات الخبرة',
    'about.stats.countries': 'الدول المخدومة',
    'about.stats.clients': 'عملاء سعداء',
    'about.stats.quality': 'جودة مضمونة',
    // Quality Page
    'quality.title': 'الجودة والشهادات',
    'quality.subtitle': 'تلبية المعايير الدولية مع كل شحنة',
    'quality.commitment': 'التزامنا بالجودة',
    'quality.testing': 'اختبارات صارمة',
    'quality.testing.desc': 'تخضع كل دفعة لاختبارات مراقبة الجودة الشاملة لضمان تلبيتها لمعاييرنا الصارمة ومتطلبات العملاء.',
    'quality.certified': 'التميز المعتمد',
    'quality.certified.desc': 'نحافظ على جميع الشهادات الدولية الرئيسية لسلامة وجودة الأغذية لضمان أعلى المعايير.',
    'quality.traceability': 'إمكانية التتبع الكاملة',
    'quality.traceability.desc': 'إمكانية تتبع كاملة من المزرعة إلى التصدير، مما يضمن الشفافية والمساءلة في كل خطوة.',
    'quality.laboratory': 'التحليل المخبري',
    'quality.laboratory.desc': 'اختبارات مخبرية متقدمة للملوثات ومعايير الجودة والامتثال للوائح الدولية.',
    'quality.certifications': 'شهاداتنا',
    'quality.iso': 'شهادة نظام إدارة سلامة الأغذية التي تضمن الإنتاج والمناولة الآمنة للأغذية',
    'quality.haccp': 'نظام تحليل المخاطر ونقاط التحكم الحرجة لسلامة الأغذية',
    'quality.organic': 'منتجات عضوية معتمدة متاحة عند الطلب لمنتجات مختارة',
    'quality.process': 'عملية الجودة لدينا',
    'quality.step1': 'اختيار المصادر',
    'quality.step1.desc': 'نختار بعناية الموردين والمزارع التي تلبي معايير الجودة لدينا وتشاركنا التزامنا بالتميز.',
    'quality.step2': 'فحص الجودة',
    'quality.step2.desc': 'تخضع المنتجات لفحص شامل للجودة والنضارة والامتثال للمواصفات.',
    'quality.step3': 'المعالجة والتعبئة',
    'quality.step3.desc': 'مرافق معالجة حديثة تضمن معالجة المنتجات بعناية وتعبئتها للحفاظ على النضارة.',
    'quality.step4': 'الاختبار النهائي',
    'quality.step4.desc': 'اختبار مخبري شامل قبل الشحن للتحقق من معايير الجودة ومعايير السلامة.',
    'quality.step5': 'التصدير والتوثيق',
    'quality.step5.desc': 'وثائق وشهادات كاملة مقدمة مع كل شحنة للامتثال الكامل وإمكانية التتبع.',
    // Contact Page
    'contact.subtitle': 'تواصل معنا للاستفسارات والطلبات',
    'contact.getintouch': 'ابق على تواصل',
    'contact.intro': 'نحن هنا للمساعدة! اتصل بنا للاستفسارات عن المنتجات أو الأسعار أو أي أسئلة حول خدماتنا.',
    'contact.address': 'العنوان',
    'contact.hours': 'ساعات العمل',
    'contact.hours.weekdays': 'الإثنين - الجمعة: 9:00 صباحًا - 6:00 مساءً',
    'contact.hours.saturday': 'السبت: 9:00 صباحًا - 1:00 مساءً',
    'contact.hours.sunday': 'الأحد: مغلق',
    'contact.form.title': 'أرسل لنا رسالة',
    'contact.form.name.label': 'الاسم',
    'contact.form.name.placeholder': 'اسمك',
    'contact.form.email.label': 'البريد الإلكتروني',
    'contact.form.email.placeholder': 'بريدك@الإلكتروني.com',
    'contact.form.company.label': 'الشركة',
    'contact.form.company.placeholder': 'شركتك',
    'contact.form.message.label': 'الرسالة',
    'contact.form.message.placeholder': 'رسالتك...',
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en')

  useEffect(() => {
    // Load language from localStorage on mount
    const savedLang = localStorage.getItem('language') as Language
    if (savedLang && ['en', 'fr', 'ar'].includes(savedLang)) {
      setLanguageState(savedLang)
      // Set document direction for Arabic
      document.documentElement.dir = savedLang === 'ar' ? 'rtl' : 'ltr'
      document.documentElement.lang = savedLang
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
    // Set document direction for Arabic
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr'
    document.documentElement.lang = lang
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
